# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: build-release-task@0
  inputs: 
    samplestring: 'yo yo'
  displayName: 'this is it'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
